### ISSUE TITLE
Pass unhandled errors back to Express

### ISSUE THREAD

**Issue by jorrit** [tommybananas/finale#11]
I would like to request that certain errors are passed back to Express so they may be handled by route handlers later. This relates to the following code in base.js:

```js
  hookChain
    .catch(errors.RequestCompleted, _.noop)
    .catch(self.model.sequelize.ValidationError, function(err) {
      var errorList = _.reduce(err.errors, function(result, error) {
        result.push({ field: error.path, message: error.message });
        return result;
      }, []);

      self.error(req, res, new errors.BadRequestError(err.message, errorList, err));
    })
    .catch(errors.FinaleError, function(err) {
      self.error(req, res, err);
    })
    .catch(function(err) {
      self.error(req, res, new errors.FinaleError(500, 'internal error', [err.message], err));
    });
```

The last catch statement seems to concern all unexpected errors which I would like to handle in Express for logging purposes.

The change seems to be quite simple, I just would like to know if the maintainer is willing to consider such a change. If so, I will make a PR.

**Comment by tommybananas** [comment]
Yep go for it, thanks
