### ISSUE TITLE
How to use AND in search ?

### ISSUE THREAD

**Issue by jbeaudoin11** [tommybananas/finale#2]
I'm looking to do something like `localhost:8080/api/v0/media?campaign_id=7&name=09`. Which should result in every media with campaign_id == 7 and where the name contains "09" (%09%)..

But i'm not able to find how to do it with "epilogue".. when i log the sequelize call i get :
![image](https://user-images.githubusercontent.com/10903391/32910717-027b1752-cad8-11e7-920e-055aec29f083.png)

What i'm looking to get is :
```
where: {
    campaign_id: 7,
    name: {
        $like: "%09%"
    }
}
```

**Comment by tommybananas** [comment]
You can use this feature to search by a single field:

```
search: {
    param: 'searchName',
    attributes: [ 'name' ]
}
```

As mentioned here: https://github.com/tommybananas/finale#search

> By default, the substring search is performed using a `{field} LIKE '%{query}%'`

**Comment by jbeaudoin11** [comment]
It's exactly what i've done ! But i wanna use multiple filter.

So i just look a little closer to the code and the problem is with `extraSearchCriteria`. For some reason it's adding param into the criteria/where field. We can see it well in my first post, there is the 2 fields + the symbol line. It work perfectly if i remove these extra criteria.

https://github.com/tommybananas/finale/blob/e8d4151b6089106f56b58896055d0aa4d8742499/lib/Controllers/list.js#L145-L146

**Comment by jbeaudoin11** [comment]
Sadly i'm not working on this project anymore so it's hard for me to reply..

Maybe it would work the way you are describing it, but i'm not sure and can't realy test it.

What I did is a patch and i'm not sure if it broke something.. but it was looking good at the moment..
