### ISSUE TITLE
del vs delete using restify

### ISSUE THREAD

**Issue by awm33** [tommybananas/finale#24]
I ran into an issue with del vs delete using restify, where is what coming up `app[self.method] is not a function`. I finally came across this line https://github.com/tommybananas/finale/blob/master/lib/Controllers/base.js#L73 and changed the name of my app to "restify".

Would it be better to just see if the app object has a key 'del' or 'delete' which value is a function?

**Comment by tommybananas** [comment]
There are two places that reference app.name, feel free to submit a pull request that passes tests if you think it can be refactored better. Thanks!
