### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by YAOHAO9** [tommybananas/finale#29]
**path:** finale-rest/lib/Controllers/base.js    
**lines:** 193

self.error(req, res, new errors.FinaleError(500, 'internal error', [err.message], err));
if (self.app.name !== 'restify') {
        next(err);
}

#### Do not send the error and use  next(err) at the same time.

**Comment by tommybananas** [comment]
It seems you are setting headers before the finale controller does it's thing. Please post more context and we can reopen.
