### ISSUE TITLE
How to add another options item while creating an model instance?

### ISSUE THREAD

**Issue by vafrcor** [tommybananas/finale#3]
I have custom Hook logic at Sequelize Model and need a custom `options` while creating an instance.
see this picture for current Finale controller.
![epilogue-finale-controller-create-options](https://user-images.githubusercontent.com/2148366/32923479-63ef3ed6-cb6a-11e7-9e91-faf63c6216b1.png)

**Comment by tommybananas** [comment]
I'm not sure I understand the question. What is an options item?

**Comment by mubaidr** [comment]
@tommybananas I think he wants to override the default get method for a resource. As by-default it will return all objects in that model, so he wants to introduce some query to limit results. 

@vafrcor I am defining custom routes in my nodejs app for these type of resources.

**Comment by mubaidr** [comment]
@vafrcor `Milestones` might be of some interests for you.

**Comment by tommybananas** [comment]
Milestones or custom routes are probably the best bet here, closing for now
