### ISSUE TITLE
Confusion with endpoints

### ISSUE THREAD

**Issue by polarathene** [tommybananas/finale#48]
Under [`resource()`](https://www.npmjs.com/package/finale-rest#resource) the docs state:

> **endpoints**

> Specify endpoints as an array with two sinatra-style URL paths in plural and singular form (e.g., ['/users', '/users/:id']).

That also states plural and singular form, but both forms are given as plural, was it meant to be `['/users', '/user/:id']`?

I have the following:

```
const userResource = finale.resource({
  model: Users,
  endpoints: ['/users',  '/users/:username'],
  actions: ['read']
});
```

When I define a resource like this, only the 2nd endpoint works(looking up that column for the given value in the URL. The docs imply that I should still be able to query the plain `/users` route with query params, such as `/users?username=polarathene` or `/users?userid=42`, instead I get the following response back:

```
{"code":"ResourceNotFound","message":"/users does not exist"}
```

If I remove the 2nd parameterized endpoint, then any query to `/users` works fine.

---

This may be specific to the Restify support, which the docs are outdated with regarding support. Some time ago in prior restify versions, the `queryParser()` and `bodyParser()` plugins were moved into `restify.plugins`, also if making the query where CORS is an issue, they also moved cors support out into middleware package, so a basic example of restify setup now is:

```
const restify = require('restify');
const corsMiddleware = require('restify-cors-middleware')
const finale = require('finale-rest')

const server = restify.createServer()

const cors = corsMiddleware({
  preflightMaxAge: 5, // Optional
  origins: ['*'], // Should whitelist actual domains in production
})

server.pre(cors.preflight)
server.use(cors.actual)

server.use(restify.plugins.queryParser());
server.use(restify.plugins.bodyParser());
```

**Comment by kurenai-ryu** [comment]
for your first question, yes, it could be that way

I think your problem is more with the 'actions' argument, the first "plural" endpoint is used for list and create, while the singular endpoint (with id argument) is used for read, update and delete.

so you specify a read endpoint but try to use a list function, of course the response will be not found or not allowed.

**Comment by polarathene** [comment]
> I think your problem is more with the 'actions' argument, the first "plural" endpoint is used for list and create, while the singular endpoint (with id argument) is used for read, update and delete.

Ah, right. Was this mentioned in the README docs? I seemed to have missed it if it was.

> so you specify a read endpoint but try to use a list function, of course the response will be not found or not allowed.

If I just have `/users` as an endpoint, and the only action `read`, I seem to get returned the first entry/row as a response, perhaps that's a bug and not meant to be allowed.

> so change your actions to ['list', 'read'] to query all the table or read a single instance

Great, that solves the confusion, thank you! I'll close this and raise a new issue on documentation regarding restify.
