### ISSUE TITLE
Restify instructions outdated

### ISSUE THREAD

**Issue by polarathene** [tommybananas/finale#49]
I opted to follow the README instructions/docs regarding the Restify support, but ran into a few issues due to changes to Restify releases.

Some time ago in prior restify versions, the `queryParser()` and `bodyParser()` plugins were moved into `restify.plugins`, also if making the query where CORS is an issue, they also moved cors support out into middleware package, so a basic example of restify setup now is:

```JS
const restify = require('restify');
const corsMiddleware = require('restify-cors-middleware')
const finale = require('finale-rest')

const server = restify.createServer()

const cors = corsMiddleware({
  preflightMaxAge: 5, // Optional
  origins: ['*'], // Should whitelist actual domains in production
})

server.pre(cors.preflight)
server.use(cors.actual)

server.use(restify.plugins.queryParser());
server.use(restify.plugins.bodyParser());
```

**Comment by polarathene** [comment]
[Covered back in Aug 2018](https://github.com/tommybananas/finale/issues/27). Leaving open since that issue was closed.

You could omit the cors part in the example above, it was something I had to do to be able to interact with the REST API in my React app. I'm aware there are alternatives such as setting up a proxy in webpack devserver  or browser, or via reverse-proxy with nginx/traefik. Most users that are learning will encounter an error in the console log about CORS being a problem though, so doesn't hurt to have a little note/example or link about handling it.

**Comment by tommybananas** [comment]
Can you make a pull request with this change? I'll happily merge it
