### ISSUE TITLE
How can I accept binary files via multer?

### ISSUE THREAD

**Issue by shamoons** [tommybananas/finale#51]
I'm doing:
```

    const audioResource = finale.resource({
        model: db.models.Audio,
        endpoints: ['/audios', '/audios/:id']
    })

    audioResource.use(multer().single("file"))
    audioResource.use(resources.audio)
```

Where `resources.audio` is:
```
module.exports = {
    create: {
        write: {
            before: (req, res, context) => {
                console.log(Object.keys(req))
                console.log(req.body)
                console.log("HERE I AM!")
                console.log(req.file)
            }
        }
    }
}
```

However, I can't access `req.file`. Is it possible to set up with the multer middleware?

**Comment by kurenai-ryu** [comment]
do you want to use multer to parse multipart form-data? or do you extensively  uses files from multer?

anyway, I managed to make it work, you can check my test repo [here](https://github.com/kurenai-ryu/finale-multer-test) but the gist is:

finale(epilogue) middleware is defined differently from a common express middleware in this case multer creates a (req,res,next) middleware, but finale(epilogue) expects (req, res, context) as specified on [its documentation](https://github.com/tommybananas/finale/blob/master/docs/Milestones.md).

as it suggest, you can call your middleware from your Milestones, but you need to return context.continue (or equivalent function/call)  that's the approach I used on my example, and I think it's the best solution.. (silly me)

anyway, as I read and read about middleware, I think what you need to do on your example is change
```javascript
//audioResource.use(multer().single("file"))
app.use(multer().single("file")) //add multer to your express app!!!
```
even if that's discouraged by multer documentation....

finally, If you intend to save the file as blob on the DB I think multer is not suited for that. just saying....

**Comment by tommybananas** [comment]
You should be able to add it as middleware before you add finale and access it in `req` in the finale hooks like any other property. Finale is typically the end of the middleware stack which is why it uses custom flow control and does not expose `next()`
