### ISSUE TITLE
Is sequelize sync mandatory for running finale?

### ISSUE THREAD

**Issue by empeje** [tommybananas/finale#55]
I tried finale on my existing project using sequelize 5 and express 4, but can't get my finale configuration working, but in a new fresh project I tried using your example and it works, I see that the different was in the `sequelize.sync` is that operations mandatory in order for finale-rest working?

**Comment by tommybananas** [comment]
No the sync function (see sequelize docs) has nothing to do with this
project

**Comment by empeje** [comment]
I've retried, and yeah it works without the sync. Please feel free to close this issue.
