### ISSUE TITLE
Associate an enpoint with a raw SQL query?

### ISSUE THREAD

**Issue by glaroc** [tommybananas/finale#65]
Is it possible to associate an enpoint with a raw SQL query ? In other words, have an endpoint that is associated to a query instead of a model?

**Comment by tommybananas** [comment]
I would say that is out of scope to this project. If the workflow doesn’t
fit within the hooks workflow I think you should just create your own
endpoint with express or whatever.

**Comment by glaroc** [comment]
Ok, thanks.
