### ISSUE TITLE
api/ base route

### ISSUE THREAD

**Issue by thboomsma** [tommybananas/finale#69]
Hello it's probably a stupid question but im running into clashes with my other project pages.

How do i change the API base link to something other than "/" .. eg. api/

Please help

**Comment by kurenai-ryu** [comment]
check the base on finale initialize api

**Comment by thboomsma** [comment]
It works, thank you!

// Initialize finale
finale.initialize({
  app: app,
  sequelize: db.Sequelize,
  base: "/api"
});

It should be added to the example code!
