### ISSUE TITLE
No new releases on GitHub since `v1.0.6`

### ISSUE THREAD

**Issue by RRozza** [tommybananas/finale#89]
It seems like Finale has had no new releases since `v1.0.6`, even though, new versions of the module were published on NPM.

The fact that `v1.0.6` was created a few years ago, makes the GitHub repo seem a bit dormant.

**Comment by tommybananas** [comment]
As mentioned in the README I do not have time to maintain this project and am looking for help in maintaining. Will try to keep publishing as CRs come in.

**Comment by RRozza** [comment]
Thanks @tommybananas, what would the process of becoming a maintainer look like?
